export const rooms = [
    {
        label: 'All',
        floor: 8,
        type: 'all',
        coordinates: [-1000, 0],
    },
    {
        label: 'Dalaköket',
        floor: 8,
        type: 'kitchen',
        coordinates: [81, 26],
    },
    {
        label: 'Test 1',
        floor: 8,
        type: 'kitchen',
        coordinates: [3, 10],
    },
    {
        label: 'Test 3',
        floor: 8,
        type: 'kitchen',
        coordinates: [95, 4],
    },
    {
        label: 'Test 4',
        floor: 8,
        type: 'bathroom',
        coordinates: [95, 66],
    },
    {
        label: 'Torsköket',
        floor: 8,
        type: 'kitchen',
        coordinates: [23, 40],
        data: {
            size: 30,
            projector: false,
            tv: false,
            phone: false,
            skype: false,
            other: '',
        },
    },
    {
        label: 'Alta',
        floor: 8,
        type: 'meeting',
        coordinates: [87, 45],
        data: {
            size: 2,
            projector: false,
            tv: false,
            phone: true,
            skype: false,
            other: '',
        },
    },
    {
        label: 'Aspen',
        floor: 8,
        type: 'meeting',
        coordinates: [92, 70],
        data: {
            size: 14,
            projector: true,
            tv: false,
            phone: true,
            skype: false,
            other: '',
        },
    },
    {
        label: 'Banff',
        floor: 8,
        type: 'meeting',
        coordinates: [94, 28],
        data: {
            size: 6,
            projector: false,
            tv: true,
            phone: true,
            skype: false,
            other: '',
        },
    },
    {
        label: 'Chamonix',
        floor: 8,
        type: 'meeting',
        coordinates: [45, 82],
        data: {
            size: 15,
            projector: true,
            tv: false,
            phone: true,
            skype: false,
            other: '',
        },
    },
    {
        label: 'Flottsbro',
        floor: 8,
        type: 'teamroom',
        coordinates: [54, 33],
        data: {
            size: 2,
            projector: false,
            tv: false,
            phone: true,
            skype: false,
        },
    },
    {
        label: 'Fernie',
        floor: 8,
        type: 'meeting',
        coordinates: [90.5, 5],
        data: {
            size: 12,
            projector: true,
            tv: false,
            phone: true,
            skype: false,
            other: '',
        },
    },
    {
        label: 'Hemsedal',
        floor: 8,
        type: 'meeting',
        coordinates: [57.5, 5],
        data: {
            size: 12,
            projector: true,
            tv: false,
            phone: true,
            skype: false,
            other: '',
        },
    },
    {
        label: 'Kitsbuhel',
        floor: 8,
        type: 'meeting',
        coordinates: [49, 18],
        data: {
            size: 2,
            projector: false,
            tv: false,
            phone: true,
            skype: false,
            other: 'No whiteboard',
        },
    },
    {
        label: 'St Anton',
        floor: 8,
        type: 'meeting',
        coordinates: [61, 73],
        data: {
            size: 14,
            projector: true,
            tv: false,
            phone: true,
            skype: false,
            other: '',
        },
    },
    {
        label: 'Stryn',
        floor: 8,
        type: 'meeting',
        coordinates: [39, 18],
        data: {
            size: 4,
            projector: false,
            tv: false,
            phone: true,
            skype: false,
            other: '',
        },
    },
    {
        label: 'Sölden',
        floor: 8,
        type: 'meeting',
        coordinates: [54, 53],
        data: {
            size: 4,
            projector: false,
            tv: false,
            phone: true,
            skype: false,
            other: '',
        },
    },
    {
        label: 'Tignes',
        floor: 8,
        type: 'meeting',
        coordinates: [43, 68],
        data: {
            size: 8,
            projector: true,
            tv: false,
            phone: false,
            skype: false,
            other: '',
        },
    },
    {
        label: 'Trysil',
        floor: 8,
        type: 'meeting',
        coordinates: [72, 18],
        data: {
            size: 8,
            projector: false,
            tv: false,
            phone: true,
            skype: false,
            other: '',
        },
    },
    {
        label: 'Vail',
        floor: 8,
        type: 'meeting',
        coordinates: [87, 55],
        data: {
            size: 7,
            projector: false,
            tv: true,
            phone: true,
            skype: false,
            other: '',
        },
    },
    {
        label: 'Åre',
        floor: 8,
        type: 'meeting',
        coordinates: [4, 13],
        data: {
            size: 12,
            projector: true,
            tv: false,
            phone: true,
            skype: false,
            other: '',
        },
    },
    {
        label: 'Teamrum DIGI Management',
        floor: 8,
        type: 'teamroom',
        coordinates: [4, 19],
        data: {
            size: 4,
            projector: false,
            tv: false,
            phone: false,
            skype: false,
            other: '',
        },
    },
    {
        label: 'Teamrum Yttrium/Lead fokus',
        floor: 8,
        type: 'teamroom',
        coordinates: [26, 43],
        data: {
            size: 4,
            projector: false,
            tv: false,
            phone: false,
            skype: false,
            other: '',
        },
    },
    {
        label: 'Teamrum Yttrium/Lead Stå',
        floor: 8,
        type: 'teamroom',
        coordinates: [32, 52],
        data: {
            size: 4,
            projector: false,
            tv: true,
            phone: false,
            skype: false,
            other: '',
        },
    },
    {
        label: 'Teamrum Yttrium/Lead Sitta',
        floor: 8,
        type: 'teamroom',
        coordinates: [29, 48],
        data: {
            size: 4,
            projector: false,
            tv: true,
            phone: false,
            skype: false,
            other: '',
        },
    },
    {
        label: 'Teamrum ROAD',
        floor: 8,
        type: 'teamroom',
        coordinates: [32, 63],
        data: {
            size: 2,
            projector: false,
            tv: true,
            phone: false,
            skype: false,
            other: '',
        },
    },
    {
        label: 'Teamrum ROAD Verbier',
        floor: 8,
        type: 'teamroom',
        coordinates: [35, 67],
        data: {
            size: 2,
            projector: false,
            tv: true,
            phone: false,
            skype: false,
            other: '',
        },
    },
    {
        label: 'Teamrum ROAD Morzine',
        floor: 8,
        type: 'teamroom',
        coordinates: [38, 71],
        data: {
            size: 2,
            projector: false,
            tv: true,
            phone: false,
            skype: false,
            other: '',
        },
    },
    {
        label: "Teamrum ROAD Val d'Isere",
        floor: 8,
        type: 'teamroom',
        coordinates: [41, 76],
        data: {
            size: 2,
            projector: false,
            tv: true,
            phone: false,
            skype: false,
            other: '',
        },
    },
    {
        label: 'Teamrum GLUE och Finanze Cortina',
        floor: 8,
        type: 'teamroom',
        coordinates: [54, 38],
        data: {
            size: 2,
            projector: false,
            tv: false,
            phone: true,
            skype: false,
        },
    },
    {
        label: 'Teamrum MIAP 2',
        floor: 8,
        type: 'teamroom',
        coordinates: [54, 43],
        data: {
            size: 2,
            projector: false,
            tv: false,
            phone: true,
            skype: false,
        },
    },
    {
        label: 'Teamrum MIAP 1',
        floor: 8,
        type: 'teamroom',
        coordinates: [54, 48],
        data: {
            size: 2,
            projector: false,
            tv: false,
            phone: true,
            skype: false,
        },
    },

    {
        label: 'Bathrooms',
        floor: 8,
        type: 'bathroom',
        coordinates: [23, 28],
        data: {},
    },
    {
        label: 'Bathrooms',
        floor: 8,
        type: 'bathroom',
        coordinates: [81, 18],
        data: {},
    },
    {
        label: 'Bathrooms',
        floor: 8,
        type: 'bathroom',
        coordinates: [40, 63],
        data: {},
    },
    {
        label: 'Bathrooms',
        floor: 8,
        type: 'bathroom',
        coordinates: [87, 65],
        data: {},
    },
    {
        label: 'Printers',
        floor: 8,
        type: 'printer',
        coordinates: [94, 9],
        data: {},
    },
    {
        label: 'Printers',
        floor: 8,
        type: 'printer',
        coordinates: [15, 28],
        data: {},
    },
    {
        label: 'Printers',
        floor: 8,
        type: 'printer',
        coordinates: [51, 89],
        data: {},
    },
    {
        label: 'Printers',
        floor: 8,
        type: 'printer',
        coordinates: [83, 65],
        data: {},
    },
];

export default rooms;
