export const Rooms = [
    {
        label: 'All',
        floor: 8,
        type: 'all',
        coordinates: [-1000, 0],
    },
    {
        label: 'Dalaköket',
        floor: 8,
        type: 'kitchen',
        coordinates: [80, 27],
    },
    {
        label: "Torsköket",
        floor: 8,
        type: 'kitchen',
        coordinates: [23, 40],
        data: {
            size: 30,
            projector: false,
            tv: false,
            phone: false,
            skype: false,
            other: '',
        },
    },
    {
        label: "Alp d'Huez",
        floor: 2,
        type: 'meeting',
        coordinates: [0, 0],
        data: {
            size: 2,
        },
    },
    {
        label: 'Alta',
        floor: 8,
        type: 'meeting',
        coordinates: [87, 45],
        data: {
            size: 2,
            projector: false,
            tv: false,
            phone: true,
            skype: false,
            other: '',
        },
    },
    {
        label: 'Aspen',
        floor: 8,
        type: 'meeting',
        coordinates: [92,70],
        data: {
            size: 14,
            projector: true,
            tv: false,
            phone: true,
            skype: false,
            other: '',
        },
    },
    {
        label: 'Banff',
        floor: 8,
        type: 'meeting',
        coordinates: [92, 28],
        data: {
            size: 6,
            projector: false,
            tv: true,
            phone: true,
            skype: false,
            other: '',
        },
    },
    {
        label: "Chamonix",
        floor: 8,
        type: 'meeting',
        coordinates: [47, 80],
        data: {
            size: 15,
            projector: true,
            tv: false,
            phone: true,
            skype: false,
            other: '',
        },
    },
    {
        label: "Flottsbro",
        floor: 8,
        type: 'teamroom',
        coordinates: [54, 33],
        data: {
            size: 2,
            projector: false,
            tv: false,
            phone: true,
            skype: false,
        },
    },
    {
        label: 'Fernie',
        floor: 8,
        type: 'meeting',
        coordinates: [90, 10],
        data: {
            size: 12,
            projector: true,
            tv: false,
            phone: true,
            skype: false,
            other: '',
        },
    },
    {
        label: 'Hemsedal',
        floor: 8,
        type: 'meeting',
        coordinates: [57, 10],
        data: {
            size: 12,
            projector: true,
            tv: false,
            phone: true,
            skype: false,
            other: '',
        },
    },
    {
        label: 'Kitsbuhel',
        floor: 8,
        type: 'meeting',
        coordinates: [48, 20],
        data: {
            size: 2,
            projector: false,
            tv: false,
            phone: true,
            skype: false,
            other: 'No whiteboard',
        },
    },
    {
        label: "St Anton",
        floor: 8,
        type: 'meeting',
        coordinates: [60, 72],
        data: {
            size: 14,
            projector: true,
            tv: false,
            phone: true,
            skype: false,
            other: '',
        },
    },
    {
        label: 'Stryn',
        floor: 8,
        type: 'meeting',
        coordinates: [39, 20],
        data: {
            size: 4,
            projector: false,
            tv: false,
            phone: true,
            skype: false,
            other: '',
        },
    },
    {
        label: "Sölden",
        floor: 8,
        type: 'meeting',
        coordinates: [54, 53],
        data: {
            size: 4,
            projector: false,
            tv: false,
            phone: true,
            skype: false,
            other: '',
        },
    },
    {
        label: "Tignes",
        floor: 8,
        type: 'meeting',
        coordinates: [44, 68],
        data: {
            size: 8,
            projector: true,
            tv: false,
            phone: false,
            skype: false,
            other: '',
        },
    },
    {
        label: 'Trysil',
        floor: 8,
        type: 'meeting',
        coordinates: [72, 20],
        data: {
            size: 8,
            projector: false,
            tv: false,
            phone: true,
            skype: false,
            other: '',
        },
    },
    {
        label: 'Vail',
        floor: 8,
        type: 'meeting',
        coordinates: [87, 55],
        data: {
            size: 7,
            projector: false,
            tv: true,
            phone: true,
            skype: false,
            other: '',
        },
    },
    {
        label: "Åre",
        floor: 8,
        type: 'meeting',
        coordinates: [4, 15],
        data: {
            size: 12,
            projector: true,
            tv: false,
            phone: true,
            skype: false,
            other: '',
        },
    },
    {
        label: "Teamrum DIGI Management",
        floor: 8,
        type: 'teamroom',
        coordinates: [4, 21],
        data: {
            size: 4,
            projector: false,
            tv: false,
            phone: false,
            skype: false,
            other: '',
        },
    },
    {
        label: "Teamrum Yttrium/Lead fokus",
        floor: 8,
        type: 'teamroom',
        coordinates: [26, 44],
        data: {
            size: 4,
            projector: false,
            tv: false,
            phone: false,
            skype: false,
            other: '',
        },
    },
    {
        label: "Teamrum Yttrium/Lead Stå",
        floor: 8,
        type: 'teamroom',
        coordinates: [32, 52],
        data: {
            size: 4,
            projector: false,
            tv: true,
            phone: false,
            skype: false,
            other: '',
        },
    },
    {
        label: "Teamrum Yttrium/Lead Sitta",
        floor: 8,
        type: 'teamroom',
        coordinates: [29, 48],
        data: {
            size: 4,
            projector: false,
            tv: true,
            phone: false,
            skype: false,
            other: '',
        },
    },
    {
        label: "Teamrum ROAD",
        floor: 8,
        type: 'teamroom',
        coordinates: [34, 62],
        data: {
            size: 2,
            projector: false,
            tv: true,
            phone: false,
            skype: false,
            other: '',
        },
    },
    {
        label: "Teamrum ROAD Verbier",
        floor: 8,
        type: 'teamroom',
        coordinates: [37, 66],
        data: {
            size: 2,
            projector: false,
            tv: true,
            phone: false,
            skype: false,
            other: '',
        },
    },
    {
        label: "Teamrum ROAD Morzine",
        floor: 8,
        type: 'teamroom',
        coordinates: [40, 70],
        data: {
            size: 2,
            projector: false,
            tv: true,
            phone: false,
            skype: false,
            other: '',
        },
    },
    {
        label: "Teamrum ROAD Val d'Isere",
        floor: 8,
        type: 'teamroom',
        coordinates: [43, 75],
        data: {
            size: 2,
            projector: false,
            tv: true,
            phone: false,
            skype: false,
            other: '',
        },
    },
    {
        label: "Teamrum GLUE och Finanze Cortina",
        floor: 8,
        type: 'teamroom',
        coordinates: [54, 38],
        data: {
            size: 2,
            projector: false,
            tv: false,
            phone: true,
            skype: false,
        },
    },
    {
        label: "Teamrum MIAP 2",
        floor: 8,
        type: 'teamroom',
        coordinates: [54, 43],
        data: {
            size: 2,
            projector: false,
            tv: false,
            phone: true,
            skype: false,
        },
    },
    {
        label: "Teamrum MIAP 1",
        floor: 8,
        type: 'teamroom',
        coordinates: [54, 48],
        data: {
            size: 2,
            projector: false,
            tv: false,
            phone: true,
            skype: false,
        },
    },

    {
        label: 'Bathroom',
        floor: 8,
        type: 'bathroom',
        coordinates: [23, 28],
        data: {},
    },
    {
        label: 'Bathroom',
        floor: 8,
        type: 'bathroom',
        coordinates: [81, 20],
        data: {},
    },
    {
        label: 'Bathroom',
        floor: 8,
        type: 'bathroom',
        coordinates: [40, 63],
        data: {},
    },
    {
        label: 'Bathroom',
        floor: 8,
        type: 'bathroom',
        coordinates: [87, 65],
        data: {},
    },
    {
        label: 'Printer',
        floor: 8,
        type: 'printer',
        coordinates: [94, 10],
        data: {},
    },
    {
        label: 'Printer',
        floor: 8,
        type: 'printer',
        coordinates: [15, 28],
        data: {},
    },
    {
        label: "Printer",
        floor: 8,
        type: 'printer',
        coordinates: [50, 84],
        data: {},
    },
    {
        label: "Printer",
        floor: 8,
        type: 'printer',
        coordinates: [83, 65],
        data: {},
    }
];

export default Rooms;


    


    

        

        
            

            

                

                

                    

                            